### PR TITLE
FIX: SilverStripe 4 upgrade

### PR DESCRIPTION
**Pull request by phptek**
- Added namespaces and namespaced template ref
- Used JS array notation
- Updated README
- Updated composer.json
- Updated for PSR2
- Allows group-heading even with single child groups
- Uses $menu_icon and $menu_title for icons+titles respectively
- Tidied-up CSS

### CODE REVIEW

**Comment by nglasl** [comment]
@phptek is this forked from https://github.com/symbiote/silverstripe-grouped-cms-menu/pull/30, or a separate SS4 upgrade?

**Comment by phptek** [comment]
Agh! I didn't see that, I only looked in existing branches, didn't check PRs!! Pick the one that works/looks the best?

**Comment by nglasl** [comment]
@phptek I mainly ask because the other PR is waiting on some changes before it can be merged, but it hasn't been very active. Yours might have them covered, but it's worth taking a quick look at the feedback there to see if there's anything you might have missed with yours? I'll book some time in to review this and we can go from there. Thanks for the contribution :)

**Comment by phptek** [comment]
@nglasl Thanks for the feedback, I'll have a look at #30 and patch accordingly if need be, Cheers.

**Comment by phptek** [comment]
@nglasl Response below. Caveat: This is an upgrade and a bit of a refactor. Apologies for perhaps making your review work a little harder!

1). Upgrader.yml: I'm not super-familliar with the module in an SS3 context, nor with the upgrader itself which I didn't use. It misses things sometimes (the last time I used it, admittedly was a while ago. Seeing that this is just one class, I did the "upgrade" manually
2). Config just uses $this->getOwner()->config() attached to a FQCN for LeftAndMain declared in _config/groupedcmsmenu.yml
3). Re: Changing to using "items", my fork has no such array key
4). See above
5). Already done
6). Arrow styling. I omitted doing this as for my own uses, It wasn't necessary. 
7). Uses the default CMS colour for a highlighted sub-menu item
8). Already done
9). init() is kept, as it calls Requirements::css() for fetching GroupedCmsMenu.css

Additional Stuff

1). Formely, devs were restricted to showing a parent, collapsible menu, and sub-menu only for >=2 items. It now accepts >= 1 and will still show the parent
2). Formely, the YML config format as documented didn't work, the YML parser barfed on it. It now works as follows:

```
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Symbiote\GroupedCmsMenu\Admin\GroupedCmsMenu
  menu_groups:
    MyParentMenu:
      children:
        # Use dash separators, due to how GroupedList::groupBy() behaves
        - 'Foo-Bar-FooBarAdmin'
        - 'Foo-Bar-FooBarFooAdmin'
        - 'Bar-Foo-BarFooAdmin'
```

You can also add an icon for each parent in YML:

```
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Symbiote\GroupedCmsMenu\Admin\GroupedCmsMenu
  menu_groups:
    MyParentMenu:
      icon: 'rocket'
      children:
        # Use dash separators, due to how GroupedList::groupBy() behaves
        - 'Foo-Bar-FooBarAdmin'
        - 'Foo-Bar-FooBarFooAdmin'
        - 'Bar-Foo-BarFooAdmin'
```

Comments/feedback welcome :-)

**Comment by nglasl** [comment]
Sounds good @phptek, I'll block some time out soon to really dig into this and hopefully we can get it merged.

**Comment by phptek** [comment]
Hi @nglasl any progress on this? I'm happy to work with you to resolve any questions, issues or implentation problems.

**Comment by nglasl** [comment]
@phptek sorry for the delayed response, it's been a super busy month. I've blocked out today to look at this, so I'll be in touch with any findings. I might make a list below and just update it as I go:

- The first README example is missing `menu_groups`. I used this to give the upgrade a test and started wondering why nothing was changing :)

**Comment by nglasl** [comment]
@phptek this looks great, fantastic work. Please see my findings above and let me know if you have any questions. Keen to get this merged through very soon!

**Comment by phptek** [comment]
Many thanks for the thorough review. The ball's in my court now!

**Comment by dcentrica** [comment]
Many thanks @nglasl for the detailed review. I have patched the feature branch. See my notes/questions below:

> The first README example is missing menu_groups

Fixed.

> There's two CMSPagesController: references in the examples,

Fixed.

> I couldn't seem to get the menu_groups_alphabetical_sorting working,

Can you give me your YML config to verify and patch please?

> needs to be just sitemap to work.

Fixed.

> should have - characters rather than /

Fixed.

> The examples don't need extensions: as this is already added

Fixed.

> Should this (and the other one further below) be $class::create rather than new $class

Yes! Fixed.

> Can the images folder be removed if it's no longer being used? 

Unused, deleted. Fixed.

> PSR-4 autoloading is missing, but not a requirement.

Added. Fixed.

**Comment by nglasl** [comment]
Awesome, thanks for jumping onto that so quickly @phptek!

Regarding the `menu_groups_alphabetical_sorting`, I just used the README example and ended up renaming the `ReportAdmin` to `ZReportAdmin` to see if it was doing anything. This shouldn't affect the sorting until you change https://github.com/symbiote/silverstripe-grouped-cms-menu/pull/31/files#diff-b067ed9902fd54e73a70bf0535e77b7cR191 to `ChildTitle`.

**Comment by phptek** [comment]
Yeah, I tried making that change and flushed but I saw no difference. I guess I need to know "what should that config setting do?" 1). Sort child items within each group 2). Sort the order of the groups (I'd hope that was controlled by menu_priority though)

**Comment by nglasl** [comment]
It should be number 1, I'm thinking I hit the merge button on this and I can come back and make the `menu_groups_alphabetical_sorting` change after giving it another play (if needed). How does that sound to you?

**Comment by phptek** [comment]
@nglasl merge sounds good to me! One less fork in my project ;-)

**Comment by nglasl** [comment]
@phptek just an update, this is all tagged 4.0.0 now. If there's any issues, please let me know. Thanks again for your hard work in getting this over the line :100:

**Pull request merged**
