### PR TITLE
Dev/ss4

### PR DESCRIPTION
**Pull request by fonsekaean**
SilverStripe 4 compatibility and update the read me docs

### CODE REVIEW

**Comment by brasileric** [comment]
any news about this pull request for ss4 branche?

**Comment by nglasl** [comment]
@fonsekaean thanks for pull requesting this! @brasileric I've assigned this to myself and will review it ASAP with a view to merging, thanks for touching base.

**Comment by nglasl** [comment]
@fonsekaean and @brasileric I've completed my review of this, and it's looking great. There are a few things that need fixing, and a few things that can be tidied up. Once these are done, I can hit the merge button and create a stable release :)

Required:

- This needs a https://github.com/nglasl/silverstripe-misdirection/blob/master/.upgrade.yml file, which should have been automatically created when running the upgrader (https://github.com/silverstripe/silverstripe-upgrader). Thankfully it'll only have a single entry, so you can just manually push this in.
- https://github.com/symbiote/silverstripe-grouped-cms-menu/blob/2ad5805aa62ba2388a3f32f0cb8a174c3177bda9/src/Extensions/GroupedCmsMenu.php#L97 is missing a `::class`, so it'll not resolve the namespace correctly. This should have also been picked up by the upgrader, so I assume you didn't use it here?
- Can you please add a small note into the README about upgrading to SS4, and the change to using `items:`?
- Following on from the above, can you please also check that `$menuItems['items']` `isset`? I'd say we should throw an exception here, as people are likely to upgrade from SS3 and forget to convert their config over.
- Can you please delete the `_config.php` file? This isn't needed if it's empty and a `_config` folder exists.

Minor:

- The composer installer name can go since this is now a vendor module.
- Can probably just remove the `init` rather than commenting it out.

Awesome work here, looking forward to getting this one back to master and SS4 compatible.

**Comment by wilr** [comment]
@fonsekaean Keen to make those above changes so there can be a release?

**Comment by normann** [comment]
> @fonsekaean Keen to make those above changes so there can be a release?

I am also hungry to use the SS4 version of the module, please make the changes requested ASAP, thanks

**Comment by liamwalder** [comment]
Very keen on getting this into one of my projects. There a time frame on we expect this to be completed? Thanks in advance.

**Comment by nglasl** [comment]
@wilr, @normann, @liamwalder would anyone be keen on picking up this PR and making the remaining changes? I'm more than happy to merge and tag a release once that's done. If this is still hanging around when my time starts to free up, I should be able to jump on this to make the remaining changes.

**Comment by nglasl** [comment]
Just an update on this, the SS4 upgrade over at https://github.com/symbiote/silverstripe-grouped-cms-menu/pull/31 has been merged based solely on activity, so this is no longer required.

I did however just want to comment here just to thank you again for your hard work behind this contribution :)

**Pull request closed without merging**
